const express = require("express");
const Database = require("better-sqlite3");
const path = require("path");

const app = express();
const db = new Database("harvix.db");
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

db.exec(`
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT UNIQUE NOT NULL,
 role TEXT NOT NULL DEFAULT 'user'
);
CREATE TABLE IF NOT EXISTS nodes (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 host TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'offline'
);
CREATE TABLE IF NOT EXISTS servers (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 owner_id INTEGER NOT NULL,
 node_id INTEGER,
 ram_mb INTEGER NOT NULL,
 disk_mb INTEGER NOT NULL,
 cpu_vcpu REAL NOT NULL,
 status TEXT NOT NULL DEFAULT 'stopped',
 software TEXT DEFAULT 'Paper',
 version TEXT DEFAULT '1.21.x',
 alias_ip TEXT DEFAULT ''
);
`);
if (!db.prepare("SELECT id FROM users WHERE username='admin'").get())
  db.prepare("INSERT INTO users(username,role) VALUES('admin','admin')").run();
if (!db.prepare("SELECT id FROM users WHERE username='demo'").get())
  db.prepare("INSERT INTO users(username,role) VALUES('demo','user')").run();

const USER_LIMITS={ram_mb:4096,disk_mb:5120,cpu_vcpu:1};
const getUser=id=>db.prepare("SELECT * FROM users WHERE id=?").get(id);

app.get("/api/health",(_,res)=>res.json({ok:true,name:"HarvixPanel",version:"0.2.0"}));

app.get("/api/servers",(req,res)=>{
 const user=getUser(Number(req.query.user_id||2));
 if(!user)return res.status(404).json({error:"user not found"});
 const rows=user.role==="admin"
  ? db.prepare("SELECT * FROM servers ORDER BY id DESC").all()
  : db.prepare("SELECT * FROM servers WHERE owner_id=? ORDER BY id DESC").all(user.id);
 res.json(rows.map(x=>user.role==="admin"?x:{...x,alias_ip:""}));
});

app.post("/api/servers",(req,res)=>{
 const {name,owner_id=2,node_id=null,ram_mb=1024,disk_mb=1024,cpu_vcpu=1,software="Paper",version="1.21.x"}=req.body;
 const user=getUser(Number(owner_id));
 if(!user)return res.status(404).json({error:"owner not found"});
 if(!name)return res.status(400).json({error:"server name is required"});
 if(user.role!=="admin" && (Number(ram_mb)>4096||Number(disk_mb)>5120||Number(cpu_vcpu)>1))
   return res.status(403).json({error:"Normal user limit: 4 GB RAM, 5 GB disk, 1 vCPU"});
 const r=db.prepare(`INSERT INTO servers(name,owner_id,node_id,ram_mb,disk_mb,cpu_vcpu,software,version)
 VALUES(?,?,?,?,?,?,?,?)`).run(name,user.id,node_id,+ram_mb,+disk_mb,+cpu_vcpu,software,version);
 res.json({ok:true,id:r.lastInsertRowid});
});

app.post("/api/servers/:id/:action",(req,res)=>{
 const allowed=["start","stop","restart"];
 if(!allowed.includes(req.params.action))return res.status(400).json({error:"invalid action"});
 const status=req.params.action==="stop"?"stopped":"running";
 db.prepare("UPDATE servers SET status=? WHERE id=?").run(status,+req.params.id);
 res.json({ok:true,status});
});

/* Admin-only IP Alias. This is a display alias, not DNS/proxy magic. */
app.put("/api/servers/:id/alias",(req,res)=>{
 const user=getUser(Number(req.body.user_id||2));
 if(!user||user.role!=="admin")return res.status(403).json({error:"Admin only"});
 const alias=String(req.body.alias_ip||"").trim();
 if(alias.length>255)return res.status(400).json({error:"Alias too long"});
 db.prepare("UPDATE servers SET alias_ip=? WHERE id=?").run(alias,+req.params.id);
 res.json({ok:true,alias_ip:alias});
});

app.get("/api/servers/:id/files",(_,res)=>res.json({ok:true,message:"File manager API is reserved for the node agent phase."}));
app.get("/api/servers/:id/sftp",(_,res)=>res.json({ok:true,message:"SFTP credentials will be generated by the node agent."}));
app.get("/api/servers/:id/plugins",(_,res)=>res.json({ok:true,message:"Plugin installer UI ready; package installation comes with the node agent."}));
app.get("/api/servers/:id/mods",(_,res)=>res.json({ok:true,message:"Mod manager UI ready; package installation comes with the node agent."}));
app.post("/api/servers/:id/votifier-test",(_,res)=>res.json({ok:true,message:"Votifier test endpoint placeholder."}));

app.listen(process.env.PORT||3000,()=>console.log("HarvixPanel v0.2.0 running"));
